# CMake generated Testfile for 
# Source directory: /src/cmake-3.12.3/Tests/CMakeTests
# Build directory: /src/cmake-3.12.3/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMake.List "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ListTest.cmake")
add_test(CMake.VariableWatch "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/VariableWatchTest.cmake")
add_test(CMake.Include "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/IncludeTest.cmake")
add_test(CMake.FindBase "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/FindBaseTest.cmake")
add_test(CMake.Toolchain "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ToolchainTest.cmake")
add_test(CMake.GetFilenameComponentRealpath "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
add_test(CMake.Version "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/VersionTest.cmake")
add_test(CMake.Message "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/MessageTest.cmake")
add_test(CMake.File "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/FileTest.cmake")
add_test(CMake.ImplicitLinkInfo "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
add_test(CMake.ModuleNotices "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ModuleNoticesTest.cmake")
add_test(CMake.GetProperty "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/GetPropertyTest.cmake")
add_test(CMake.If "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/IfTest.cmake")
add_test(CMake.String "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/StringTest.cmake")
add_test(CMake.Math "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/MathTest.cmake")
add_test(CMake.CMakeMinimumRequired "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
add_test(CMake.CompilerIdVendor "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/CompilerIdVendorTest.cmake")
add_test(CMake.ProcessorCount "/src/cmake-3.12.3/bin/cmake" "-DKWSYS_TEST_EXE=/src/cmake-3.12.3/Source/kwsys/cmsysTestsCxx" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ProcessorCountTest.cmake")
add_test(CMake.PushCheckState "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/PushCheckStateTest.cmake")
add_test(CMake.While "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/WhileTest.cmake")
add_test(CMake.CMakeHostSystemInformation "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
add_test(CMake.FileDownload "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
add_test(CMake.FileDownloadBadHash "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties(CMake.FileDownloadBadHash PROPERTIES  WILL_FAIL "TRUE")
add_test(CMake.FileUpload "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/FileUploadTest.cmake")
add_test(CMake.ELF "/src/cmake-3.12.3/bin/cmake" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/ELFTest.cmake")
add_test(CMake.EndStuff "/src/cmake-3.12.3/bin/cmake" "-Ddir:STRING=/src/cmake-3.12.3/Tests/CMakeTests/EndStuffTest" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/EndStuffTest.cmake")
add_test(CMake.GetPrerequisites "/src/cmake-3.12.3/bin/cmake" "-DConfiguration:STRING=" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/GetPrerequisitesTest.cmake")
add_test(CMake.PolicyCheck "/src/cmake-3.12.3/bin/cmake" "-DCMake_BINARY_DIR:PATH=/src/cmake-3.12.3" "-DCMake_SOURCE_DIR:PATH=/src/cmake-3.12.3" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/PolicyCheckTest.cmake")
add_test(CMake.CheckSourceTree "/src/cmake-3.12.3/bin/cmake" "-DCMake_BINARY_DIR:PATH=/src/cmake-3.12.3" "-DCMake_SOURCE_DIR:PATH=/src/cmake-3.12.3" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/root" "-P" "/src/cmake-3.12.3/Tests/CMakeTests/CheckSourceTreeTest.cmake")
